# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96ca4baac9f2b2eec5bbb678b31e9459d5f079abec3babd7d070e6d6337a8e1a7e6daf39a2b13cc7477efcc3d1dbf563fd877a6d9a8f8be4f3db82da0d92d3b

test:
  secret_key_base: 62782bd672f33b72cbef0786fa4c5d9e6e9875a6e5a8b6239bcd7adf0f53951b3dcea5aeffb5c5eb677abfc6dc01f94a20208a837d208c655014b818aea6dc18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
